package playground

import (
	"bytes"
	"fmt"
	"text/template"
)

const standaloneComposeTemplate = `# MiUp Milvus Playground - Standalone Mode
# Generated by miup, do not edit manually

services:
  etcd:
    container_name: milvus-etcd-{{.Tag}}
    image: quay.io/coreos/etcd:v{{.EtcdVersion}}
    environment:
      - ETCD_AUTO_COMPACTION_MODE=revision
      - ETCD_AUTO_COMPACTION_RETENTION=1000
      - ETCD_QUOTA_BACKEND_BYTES=4294967296
      - ETCD_SNAPSHOT_COUNT=50000
    volumes:
      - etcd_data:/etcd
    command: etcd -advertise-client-urls=http://127.0.0.1:2379 -listen-client-urls http://0.0.0.0:2379 --data-dir /etcd
    healthcheck:
      test: ["CMD", "etcdctl", "endpoint", "health"]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      - milvus

  minio:
    container_name: milvus-minio-{{.Tag}}
    image: minio/minio:{{.MinioVersion}}
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    ports:
      - "{{.MinioPort}}:9000"
      - "{{.MinioConsole}}:9001"
    volumes:
      - minio_data:/minio_data
    command: minio server /minio_data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      - milvus

  standalone:
    container_name: milvus-standalone-{{.Tag}}
    image: milvusdb/milvus:{{.MilvusVersion}}
    command: ["milvus", "run", "standalone"]
    security_opt:
      - seccomp:unconfined
    environment:
      ETCD_ENDPOINTS: etcd:2379
      MINIO_ADDRESS: minio:9000
    volumes:
      - milvus_data:/var/lib/milvus
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9091/healthz"]
      interval: 30s
      start_period: 90s
      timeout: 20s
      retries: 3
    ports:
      - "{{.MilvusPort}}:19530"
      - "9091:9091"
    depends_on:
      etcd:
        condition: service_healthy
      minio:
        condition: service_healthy
    networks:
      - milvus
{{if .WithMonitor}}
  prometheus:
    container_name: milvus-prometheus-{{.Tag}}
    image: prom/prometheus:latest
    ports:
      - "{{.PrometheusPort}}:9090"
    volumes:
      - prometheus_data:/prometheus
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.enable-lifecycle'
    networks:
      - milvus

  grafana:
    container_name: milvus-grafana-{{.Tag}}
    image: grafana/grafana:latest
    ports:
      - "{{.GrafanaPort}}:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus
    networks:
      - milvus
{{end}}
networks:
  milvus:
    driver: bridge

volumes:
  etcd_data:
  minio_data:
  milvus_data:
{{- if .WithMonitor}}
  prometheus_data:
  grafana_data:
{{- end}}
`

const clusterComposeTemplate = `# MiUp Milvus Playground - Cluster Mode
# Generated by miup, do not edit manually

services:
  etcd:
    container_name: milvus-etcd-{{.Tag}}
    image: quay.io/coreos/etcd:v{{.EtcdVersion}}
    environment:
      - ETCD_AUTO_COMPACTION_MODE=revision
      - ETCD_AUTO_COMPACTION_RETENTION=1000
      - ETCD_QUOTA_BACKEND_BYTES=4294967296
      - ETCD_SNAPSHOT_COUNT=50000
    volumes:
      - etcd_data:/etcd
    command: etcd -advertise-client-urls=http://127.0.0.1:2379 -listen-client-urls http://0.0.0.0:2379 --data-dir /etcd
    healthcheck:
      test: ["CMD", "etcdctl", "endpoint", "health"]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      - milvus

  minio:
    container_name: milvus-minio-{{.Tag}}
    image: minio/minio:{{.MinioVersion}}
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    ports:
      - "{{.MinioPort}}:9000"
      - "{{.MinioConsole}}:9001"
    volumes:
      - minio_data:/minio_data
    command: minio server /minio_data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      - milvus

  rootcoord:
    container_name: milvus-rootcoord-{{.Tag}}
    image: milvusdb/milvus:{{.MilvusVersion}}
    command: ["milvus", "run", "rootcoord"]
    environment:
      ETCD_ENDPOINTS: etcd:2379
      MINIO_ADDRESS: minio:9000
    depends_on:
      etcd:
        condition: service_healthy
      minio:
        condition: service_healthy
    networks:
      - milvus

  proxy:
    container_name: milvus-proxy-{{.Tag}}
    image: milvusdb/milvus:{{.MilvusVersion}}
    command: ["milvus", "run", "proxy"]
    environment:
      ETCD_ENDPOINTS: etcd:2379
      MINIO_ADDRESS: minio:9000
    ports:
      - "{{.MilvusPort}}:19530"
      - "9091:9091"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9091/healthz"]
      interval: 30s
      start_period: 90s
      timeout: 20s
      retries: 3
    depends_on:
      - rootcoord
      - querycoord
      - datacoord
      - indexcoord
    networks:
      - milvus

  querycoord:
    container_name: milvus-querycoord-{{.Tag}}
    image: milvusdb/milvus:{{.MilvusVersion}}
    command: ["milvus", "run", "querycoord"]
    environment:
      ETCD_ENDPOINTS: etcd:2379
      MINIO_ADDRESS: minio:9000
    depends_on:
      etcd:
        condition: service_healthy
      minio:
        condition: service_healthy
    networks:
      - milvus

  querynode:
    container_name: milvus-querynode-{{.Tag}}
    image: milvusdb/milvus:{{.MilvusVersion}}
    command: ["milvus", "run", "querynode"]
    environment:
      ETCD_ENDPOINTS: etcd:2379
      MINIO_ADDRESS: minio:9000
    depends_on:
      - querycoord
    networks:
      - milvus

  datacoord:
    container_name: milvus-datacoord-{{.Tag}}
    image: milvusdb/milvus:{{.MilvusVersion}}
    command: ["milvus", "run", "datacoord"]
    environment:
      ETCD_ENDPOINTS: etcd:2379
      MINIO_ADDRESS: minio:9000
    depends_on:
      etcd:
        condition: service_healthy
      minio:
        condition: service_healthy
    networks:
      - milvus

  datanode:
    container_name: milvus-datanode-{{.Tag}}
    image: milvusdb/milvus:{{.MilvusVersion}}
    command: ["milvus", "run", "datanode"]
    environment:
      ETCD_ENDPOINTS: etcd:2379
      MINIO_ADDRESS: minio:9000
    depends_on:
      - datacoord
    networks:
      - milvus

  indexcoord:
    container_name: milvus-indexcoord-{{.Tag}}
    image: milvusdb/milvus:{{.MilvusVersion}}
    command: ["milvus", "run", "indexcoord"]
    environment:
      ETCD_ENDPOINTS: etcd:2379
      MINIO_ADDRESS: minio:9000
    depends_on:
      etcd:
        condition: service_healthy
      minio:
        condition: service_healthy
    networks:
      - milvus

  indexnode:
    container_name: milvus-indexnode-{{.Tag}}
    image: milvusdb/milvus:{{.MilvusVersion}}
    command: ["milvus", "run", "indexnode"]
    environment:
      ETCD_ENDPOINTS: etcd:2379
      MINIO_ADDRESS: minio:9000
    depends_on:
      - indexcoord
    networks:
      - milvus
{{if .WithMonitor}}
  prometheus:
    container_name: milvus-prometheus-{{.Tag}}
    image: prom/prometheus:latest
    ports:
      - "{{.PrometheusPort}}:9090"
    volumes:
      - prometheus_data:/prometheus
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.enable-lifecycle'
    networks:
      - milvus

  grafana:
    container_name: milvus-grafana-{{.Tag}}
    image: grafana/grafana:latest
    ports:
      - "{{.GrafanaPort}}:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus
    networks:
      - milvus
{{end}}
networks:
  milvus:
    driver: bridge

volumes:
  etcd_data:
  minio_data:
{{- if .WithMonitor}}
  prometheus_data:
  grafana_data:
{{- end}}
`

const prometheusConfigTemplate = `global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'milvus'
    static_configs:
      - targets: ['standalone:9091']
        labels:
          group: 'milvus'
`

// GenerateComposeFile generates docker-compose.yaml content
func GenerateComposeFile(cfg *Config) (string, error) {
	var tmplStr string
	if cfg.Mode == ModeCluster {
		tmplStr = clusterComposeTemplate
	} else {
		tmplStr = standaloneComposeTemplate
	}

	tmpl, err := template.New("compose").Parse(tmplStr)
	if err != nil {
		return "", fmt.Errorf("failed to parse template: %w", err)
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, cfg); err != nil {
		return "", fmt.Errorf("failed to execute template: %w", err)
	}

	return buf.String(), nil
}

// GeneratePrometheusConfig generates prometheus.yml content
func GeneratePrometheusConfig(cfg *Config) string {
	return prometheusConfigTemplate
}
