# Milvus Distributed with Pulsar Message Queue
# Use Pulsar instead of RocksMQ for better performance at scale
# Deploy: miup instance deploy <name> distributed-pulsar.yaml
apiVersion: milvus.io/v1beta1
kind: Milvus
metadata:
  name: my-milvus
  namespace: milvus
  labels:
    app: milvus
spec:
  mode: cluster
  components:
    image: milvusdb/milvus:v2.5.4
    proxy:
      replicas: 2
    queryNode:
      replicas: 2
    dataNode:
      replicas: 2
    indexNode:
      replicas: 1
  dependencies:
    etcd:
      inCluster:
        deletionPolicy: Delete
        pvcDeletion: true
        values:
          replicaCount: 3
    storage:
      inCluster:
        deletionPolicy: Delete
        pvcDeletion: true
        values:
          mode: distributed
    msgStreamType: pulsar
    pulsar:
      inCluster:
        deletionPolicy: Delete
        pvcDeletion: true
        values:
          components:
            autorecovery: false
          monitoring:
            prometheus: false
            grafana: false
          proxy:
            replicaCount: 1
            resources:
              requests:
                cpu: 200m
                memory: 256Mi
          bookkeeper:
            replicaCount: 2
            resources:
              requests:
                cpu: 200m
                memory: 512Mi
          zookeeper:
            replicaCount: 3
            resources:
              requests:
                cpu: 100m
                memory: 256Mi
          broker:
            replicaCount: 1
            resources:
              requests:
                cpu: 200m
                memory: 512Mi
