# Milvus Standalone Mode
# Minimal setup for development and testing
# Deploy: miup instance deploy <name> standalone.yaml
apiVersion: milvus.io/v1beta1
kind: Milvus
metadata:
  name: my-milvus
  namespace: milvus
  labels:
    app: milvus
spec:
  mode: standalone
  components:
    image: milvusdb/milvus:v2.5.4
  dependencies:
    etcd:
      inCluster:
        deletionPolicy: Delete
        pvcDeletion: true
        values:
          replicaCount: 1
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
    storage:
      inCluster:
        deletionPolicy: Delete
        pvcDeletion: true
        values:
          mode: standalone
          resources:
            requests:
              memory: 256Mi
